package routes

import (
	"gobase-app/controllers"
	"gobase-app/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterWebRoutes(r *gin.Engine) {
	r.Use(middleware.UserMiddleware())

	r.GET("/", controllers.LoginPage)
	r.GET("/login", controllers.LoginPage)
	r.POST("/login", controllers.LoginPost)
	r.POST("/register", middleware.AuthRequired(), middleware.PermissionContext(), middleware.RequirePermission("user_create"), controllers.CreateUser)
	r.GET("/logout", controllers.Logout)

	auth := r.Group("/")
	auth.Use(middleware.AuthRequired(), middleware.PermissionContext())
	{
		auth.GET("/dashboard", controllers.DashboardIndex)
		auth.GET("/checker/dashboard", controllers.CheckerDashboardIndex)
		auth.GET("/po-buyer/dashboard", middleware.RequirePermission("menu_ready_for_po"), controllers.POBuyerDashboardIndex)
		auth.GET("/reports/stock-opname", middleware.RequirePermission("menu_report_access"), controllers.StockOpnameReportIndex)
		auth.GET("/reports/stock-opname/:id", middleware.RequirePermission("menu_report_access"), controllers.StockOpnameReportDetail)
		auth.POST("/reports/stock-opname/:id/apply-all-submitted", middleware.RequirePermission("menu_report_access"), controllers.StockOpnameReportApplyAllSubmitted)
		auth.POST("/reports/stock-opname/:id/complete-to-po-buyer", middleware.RequirePermission("menu_report_access"), controllers.StockOpnameReportCompleteToPOBuyer)
		auth.GET("/stock-checker", middleware.RequirePermission("checker_so_input_access"), controllers.StockCheckCheckerSupplierIndex)
		auth.GET("/stock-checker/recap", middleware.RequirePermission("checker_so_recap_access"), controllers.StockCheckCheckerRecapIndex)
		auth.GET("/stock-checker/po-recap", middleware.RequirePermission("menu_ready_for_po"), controllers.StockCheckPORecapIndex)
		auth.POST("/stock-checker/po-recap/:id/status", middleware.RequireAnyPermission("menu_ready_for_po", "menu_stock_check_session_access"), controllers.StockCheckPORecapUpdateStatus)
		auth.GET("/stock-checker/sessions/:id/input", middleware.RequirePermission("checker_so_input_access"), controllers.StockCheckCheckerSessionInput)
		auth.GET("/stock-checker/sessions/:id/scan", middleware.RequirePermission("checker_so_input_access"), controllers.StockCheckCheckerSessionScanPage)
		auth.POST("/stock-checker/sessions/:id/input", middleware.RequirePermission("checker_so_input_access"), controllers.StockCheckCheckerSessionScan)
		auth.POST("/stock-checker/sessions/:id/suggest", middleware.RequirePermission("checker_so_input_access"), controllers.StockCheckCheckerSessionSuggest)
		auth.POST("/stock-checker/sessions", middleware.RequirePermission("checker_so_input_access"), controllers.StockCheckSessionStore)
		auth.GET("/stock-checker/:id/sessions/new", middleware.RequirePermission("checker_so_input_access"), controllers.StockCheckCheckerSessionCreatePage)
		auth.GET("/stock-checker/:id", middleware.RequirePermission("checker_so_input_access"), controllers.StockCheckCheckerSupplierDetail)
		auth.GET("/stock-check-sessions", middleware.RequirePermission("menu_stock_check_session_access"), controllers.StockCheckSessionIndex)
		auth.GET("/stock-check-sessions/:id", middleware.RequirePermission("menu_stock_check_session_access"), controllers.StockCheckSessionDetail)
		auth.GET("/stock-check-sessions/:id/po-detail", middleware.RequireAnyPermission("menu_stock_check_session_access", "menu_ready_for_po"), controllers.StockCheckSessionPODetail)
		auth.POST("/stock-check-sessions", middleware.RequireAnyPermission("menu_stock_check_session_access", "checker_so_input_access"), controllers.StockCheckSessionStore)
		auth.POST("/stock-check-sessions/update", middleware.RequireAnyPermission("menu_stock_check_session_access", "checker_so_input_access"), controllers.StockCheckSessionUpdate)
		auth.POST("/stock-check-sessions/:id/items/review", middleware.RequireAnyPermission("menu_stock_check_session_access", "menu_report_access"), controllers.StockCheckSessionReviewItemUpdate)
		auth.POST("/stock-check-sessions/:id/apply-all-submitted", middleware.RequireAnyPermission("menu_stock_check_session_access", "menu_report_access"), controllers.StockCheckSessionApplyAllSubmitted)
		auth.GET("/stock-check-sessions/delete/:id", middleware.RequirePermission("menu_stock_check_session_access"), controllers.StockCheckSessionDelete)

		auth.GET("/stores", middleware.RequirePermission("menu_store_access"), controllers.StoreIndex)
		auth.POST("/stores", middleware.RequirePermission("menu_store_access"), controllers.StoreStore)
		auth.POST("/stores/update", middleware.RequirePermission("menu_store_access"), controllers.StoreUpdate)
		auth.GET("/stores/delete/:id", middleware.RequirePermission("menu_store_access"), controllers.StoreDelete)
		auth.GET("/products", middleware.RequirePermission("menu_settings_access"), controllers.ProductIndex)
		auth.POST("/products", middleware.RequirePermission("menu_settings_access"), controllers.ProductStore)
		auth.POST("/products/update", middleware.RequirePermission("menu_settings_access"), controllers.ProductUpdate)
		auth.POST("/products/:id/suppliers", middleware.RequirePermission("menu_settings_access"), controllers.ProductSupplierNetworkStore)
		auth.POST("/products/:id/suppliers/:supplier_id/update", middleware.RequirePermission("menu_settings_access"), controllers.ProductSupplierNetworkUpdate)
		auth.POST("/products/:id/suppliers/:supplier_id/delete", middleware.RequirePermission("menu_settings_access"), controllers.ProductSupplierNetworkDelete)
		auth.GET("/products/delete/:id", middleware.RequirePermission("menu_settings_access"), controllers.ProductDelete)
		auth.GET("/products/:id", middleware.RequirePermission("menu_settings_access"), controllers.ProductDetail)
		auth.GET("/units", middleware.RequirePermission("menu_settings_access"), controllers.UnitIndex)
		auth.POST("/units", middleware.RequirePermission("menu_settings_access"), controllers.UnitStore)
		auth.POST("/units/update", middleware.RequirePermission("menu_settings_access"), controllers.UnitUpdate)
		auth.GET("/units/delete/:id", middleware.RequirePermission("menu_settings_access"), controllers.UnitDelete)
		auth.GET("/supplier-groups", middleware.RequirePermission("menu_settings_access"), controllers.SupplierGroupIndex)
		auth.POST("/supplier-groups", middleware.RequirePermission("menu_settings_access"), controllers.SupplierGroupStore)
		auth.POST("/supplier-groups/update", middleware.RequirePermission("menu_settings_access"), controllers.SupplierGroupUpdate)
		auth.GET("/supplier-groups/delete/:id", middleware.RequirePermission("menu_settings_access"), controllers.SupplierGroupDelete)
		auth.GET("/suppliers", middleware.RequirePermission("menu_settings_access"), controllers.SupplierIndex)
		auth.GET("/schedule", middleware.RequirePermission("menu_settings_access"), controllers.SupplierScheduleIndex)
		auth.POST("/schedule", middleware.RequirePermission("menu_settings_access"), controllers.SupplierScheduleStore)
		auth.POST("/schedule/update", middleware.RequirePermission("menu_settings_access"), controllers.SupplierScheduleUpdate)
		auth.GET("/schedule/delete/:id", middleware.RequirePermission("menu_settings_access"), controllers.SupplierScheduleDelete)
		auth.POST("/suppliers", middleware.RequirePermission("menu_settings_access"), controllers.SupplierStore)
		auth.POST("/suppliers/update", middleware.RequirePermission("menu_settings_access"), controllers.SupplierUpdate)
		auth.POST("/suppliers/:id/products", middleware.RequirePermission("menu_settings_access"), controllers.SupplierProductStore)
		auth.POST("/suppliers/:id/products/:product_id/update", middleware.RequirePermission("menu_settings_access"), controllers.SupplierProductUpdate)
		auth.POST("/suppliers/:id/products/:product_id/delete", middleware.RequirePermission("menu_settings_access"), controllers.SupplierProductDelete)
		auth.GET("/suppliers/delete/:id", middleware.RequirePermission("menu_settings_access"), controllers.SupplierDelete)
		auth.GET("/suppliers/:id", middleware.RequirePermission("menu_settings_access"), controllers.SupplierDetail)
		auth.GET("/users", middleware.RequirePermission("user_management_access"), controllers.UserIndex)
		auth.POST("/users", middleware.RequirePermission("user_create"), controllers.UserStore)
		auth.POST("/users/update", middleware.RequirePermission("user_edit"), controllers.UserUpdate)
		auth.GET("/users/delete/:id", middleware.RequirePermission("user_delete"), controllers.UserDelete)
		auth.GET("/role", middleware.RequirePermission("role_view"), controllers.RoleIndex)
		auth.GET("/roleForm", middleware.RequirePermission("role_create"), controllers.RoleFormIndex)
		auth.GET("/role/:id/edit", middleware.RequirePermission("role_edit"), controllers.RoleEdit)
		auth.POST("/role", middleware.RequirePermission("role_create"), controllers.RoleStore)
		auth.POST("/role/update", middleware.RequirePermission("role_edit"), controllers.RoleUpdate)
		auth.GET("/role/delete/:id", middleware.RequirePermission("role_delete"), controllers.RoleDelete)
	}
}
