package routes

import (
	"gobase-app/controllers"
	"gobase-app/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterWebRoutes(r *gin.Engine) {
	r.Use(middleware.UserMiddleware())

	r.GET("/", controllers.LoginPage)
	r.GET("/login", controllers.LoginPage)
	r.POST("/login", controllers.LoginPost)
	r.POST("/register", controllers.CreateUser)
	r.GET("/logout", controllers.Logout)

	auth := r.Group("/")
	auth.Use(middleware.AuthRequired(), middleware.PermissionContext())
	{
		auth.GET("/dashboard", controllers.DashboardIndex)
		auth.GET("/checker/dashboard", controllers.CheckerDashboardIndex)
		auth.GET("/reports/stock-opname", controllers.StockOpnameReportIndex)
		auth.GET("/reports/stock-opname/:id", controllers.StockOpnameReportDetail)
		auth.POST("/reports/stock-opname/:id/apply-all-submitted", controllers.StockOpnameReportApplyAllSubmitted)
		auth.GET("/stock-checker", controllers.StockCheckCheckerSupplierIndex)
		auth.GET("/stock-checker/sessions/:id/input", controllers.StockCheckCheckerSessionInput)
		auth.GET("/stock-checker/sessions/:id/scan", controllers.StockCheckCheckerSessionScanPage)
		auth.POST("/stock-checker/sessions/:id/input", controllers.StockCheckCheckerSessionScan)
		auth.POST("/stock-checker/sessions/:id/suggest", controllers.StockCheckCheckerSessionSuggest)
		auth.GET("/stock-checker/:id/sessions/new", controllers.StockCheckCheckerSessionCreatePage)
		auth.GET("/stock-checker/:id", controllers.StockCheckCheckerSupplierDetail)
		auth.GET("/stock-check-sessions", controllers.StockCheckSessionIndex)
		auth.GET("/stock-check-sessions/:id", controllers.StockCheckSessionDetail)
		auth.POST("/stock-check-sessions", controllers.StockCheckSessionStore)
		auth.POST("/stock-check-sessions/update", controllers.StockCheckSessionUpdate)
		auth.POST("/stock-check-sessions/:id/items/review", controllers.StockCheckSessionReviewItemUpdate)
		auth.GET("/stock-check-sessions/delete/:id", controllers.StockCheckSessionDelete)

		auth.GET("/stores", controllers.StoreIndex)
		auth.POST("/stores", controllers.StoreStore)
		auth.POST("/stores/update", controllers.StoreUpdate)
		auth.GET("/stores/delete/:id", controllers.StoreDelete)
		auth.GET("/products", controllers.ProductIndex)
		auth.POST("/products", controllers.ProductStore)
		auth.POST("/products/update", controllers.ProductUpdate)
		auth.POST("/products/:id/suppliers", controllers.ProductSupplierNetworkStore)
		auth.POST("/products/:id/suppliers/:supplier_id/update", controllers.ProductSupplierNetworkUpdate)
		auth.POST("/products/:id/suppliers/:supplier_id/delete", controllers.ProductSupplierNetworkDelete)
		auth.GET("/products/delete/:id", controllers.ProductDelete)
		auth.GET("/products/:id", controllers.ProductDetail)
		auth.GET("/units", controllers.UnitIndex)
		auth.POST("/units", controllers.UnitStore)
		auth.POST("/units/update", controllers.UnitUpdate)
		auth.GET("/units/delete/:id", controllers.UnitDelete)
		auth.GET("/supplier-groups", controllers.SupplierGroupIndex)
		auth.POST("/supplier-groups", controllers.SupplierGroupStore)
		auth.POST("/supplier-groups/update", controllers.SupplierGroupUpdate)
		auth.GET("/supplier-groups/delete/:id", controllers.SupplierGroupDelete)
		auth.GET("/suppliers", controllers.SupplierIndex)
		auth.POST("/suppliers", controllers.SupplierStore)
		auth.POST("/suppliers/update", controllers.SupplierUpdate)
		auth.POST("/suppliers/:id/products", controllers.SupplierProductStore)
		auth.POST("/suppliers/:id/products/:product_id/update", controllers.SupplierProductUpdate)
		auth.POST("/suppliers/:id/products/:product_id/delete", controllers.SupplierProductDelete)
		auth.GET("/suppliers/delete/:id", controllers.SupplierDelete)
		auth.GET("/suppliers/:id", controllers.SupplierDetail)
		auth.GET("/users", middleware.RequirePermission("user_management_access"), controllers.UserIndex)
		auth.POST("/users", middleware.RequirePermission("user_create"), controllers.UserStore)
		auth.POST("/users/update", middleware.RequirePermission("user_edit"), controllers.UserUpdate)
		auth.GET("/users/delete/:id", middleware.RequirePermission("user_delete"), controllers.UserDelete)
		auth.GET("/role", controllers.RoleIndex)
		auth.GET("/roleForm", controllers.RoleFormIndex)
		auth.GET("/role/:id/edit", middleware.RequirePermission("role_edit"), controllers.RoleEdit)
		auth.POST("/role", middleware.RequirePermission("role_create"), controllers.RoleStore)
		auth.POST("/role/update", middleware.RequirePermission("role_edit"), controllers.RoleUpdate)
		auth.GET("/role/delete/:id", middleware.RequirePermission("role_delete"), controllers.RoleDelete)
	}
}
